### ISSUE TITLE
Text containing newlines are rejected by KeywordHandler

### ISSUE THREAD

**Issue by knightsamar** [rapidsms/rapidsms#439]
A message string like the following is **rejected** by a KeywordHandler implementation because they contain newlines.

```
HELLO This sentence contains a newline \n before these bunch of words. And another newline is at the end \n
```

Where **HELLO** is the keyword.

**Comment by dpoirier** [comment]
How could this happen in practice?

**Comment by jthurner** [comment]
Android lets you insert newlines. Some versions have the key always visible, others hide it unless you hold shift.

So it could happen that users include a newline by accident (however rarely?). But if I understood correctly, knightsamar wanted to use newlines for parsing.

**Comment by vkurup** [comment]
Seems (to me) like this would be a reasonable change to make then.
