### ISSUE TITLE
make compatible with Django 1.7+

### ISSUE THREAD

**Issue by johanneswilm** [rapidsms/rapidsms#441]
I get a warning message every time I try to run the app (about three times):

rapidsms.App.active: (1_6.W002) BooleanField does not have a default value.
	HINT: Django 1.6 changed the default value of BooleanField from False to None. See https://docs.djangoproject.com/en/1.6/ref/models/fields/#booleanfield for more information.

which I think refers to this https://github.com/rapidsms/rapidsms/blob/develop/rapidsms/models.py#L75

Changing the line to 

active = models.BooleanField(default=False)

makes the error go away

**Comment by vkurup** [comment]
Completed with the 0.18.0 release. Now to work on 1.8!
