### ISSUE TITLE
Template URL for 0.19.0 broken

### ISSUE THREAD

**Issue by TekThis** [rapidsms/rapidsms#458]
As per installation documentation at:
http://rapidsms.readthedocs.org/en/latest/intro/install/

This line fails with 404 error:
django-admin.py startproject --template=https://github.com/rapidsms/rapidsms-project-template/zipball/release-0.19.0 --extension=py,rst my_project_name

**Comment by vkurup** [comment]
Thank you for your report! This should now be fixed in the latest release.
