### ISSUE TITLE
rapidsms.org domain name is hijacked?

### ISSUE THREAD

**Issue by Mariatta** [rapidsms/rapidsms#502]
On the GitHub landing page of the repo, it has a link to rapidsms dot org
![Screenshot 2024-10-10 at 9 46 06 PM](https://github.com/user-attachments/assets/10f54879-429e-4569-8814-e89be29f8f85)

That website seemed to be a foreign gambling website.

Should the url be changed to https://rapidsms.readthedocs.io/en/latest/ instead?

**Comment by tobiasmcnulty** [comment]
@Mariatta Thanks for the catch! I updated GitHub and removed the link from the docs template.

@ewheeler Do you happen to know who owned this domain and if it's possible we're within the window where we could get it back? Caktus is happy to take over paying for it if needed.

**Comment by ewheeler** [comment]
@tobiasmcnulty from what i can tell, i transferred it out of a former colleague's namecheap account around 2020. i thought it would have been to myself, but i've looked at all the registrars where i have domains and don't see any record of it. sorry, i don't recall where/who took over the registration in 2020.

**Comment by tobiasmcnulty** [comment]
@ewheeler No problem, thanks for checking! Hope all is well!
